name: "sample workflow"
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    container: ghcr.io/dbt-labs/dbt-bigquery:1.3.latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/998338573837/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: "my-service-account@sandbox-ryutah-301812.iam.gserviceaccount.com"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: "417.0.1"
      - name: "run sample"
        shell: bash
        run: bq version

      # - name: "run sample"
      #   shell: bash
      #   run: |
      #     # artifact の命名ルールとして / が使えないため、変換が必要だった
      #     echo "artifact_key=`echo ${{ inputs.working_dir }} | sed -e 's/\//-/g'`" >> $GITHUB_ENV
      #
      # - name: "Deploy to Cloud Run"
      #   id: deploy-run
      #   uses: google-github-actions/deploy-cloudrun@v0
      #   with:
      #     image: ubuntu
      #     service: ${{ inputs.service_name }}
      #     region: ${{ inputs.region }}
      #     project_id: ${{ inputs.project_id}}
      #     tag: ${{ inputs.tag }}
      #     timeout: ${{ inputs.timeout }}
      #     flags: ${{ inputs.flags }}
